### ISSUE TITLE
Remove generic component and standardize table components

### ISSUE THREAD

**Issue by ketphan02** [Teamable-Analytics/teamable-frontend#49]
nit;

I would be wary of trying to make this component generalizable. Something Abhinav shared earlier in the project is the notion from shadcn's creator basically saying "every table is unique" and I'm inclined to agree. I don't think I've ever seen a generic table component not be super annoying to work with.

My belief for the project is we should standardize the individual pieces of the table (i.e. pagination componenet, filter componenet, etc), but each table should basically be like the student table and be as customized as we want it

_Originally posted by @Opeyem1a in https://github.com/Teamable-Analytics/teamable-frontend/pull/47#discussion_r1596260985_

**Comment by Opeyem1a** [comment]
Well you don't need to like remove it, there are only 2 tables, and the other one already follows this principle
